services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\Event\AfterTcaCompilationEventListener:
    tags:
      - name: event.listener
        identifier: tag-after-tca-compilation
