services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/Core/*'

  TYPO3\CMS\Extbase\:
    resource: '../Classes/Extbase/*'

  WapplerSystens\Tag\:
    resource: '../Classes/Patch/*'

  WapplerSystems\Tag\Event\AfterTcaCompilationEventListenerForTag:
    tags:
      - name: event.listener
        identifier: tag-after-tca-compilation
